import Head from 'next/head';
import Image from 'next/image';
import Feed from '../components/Feed';
import Header from '../components/Header';
import styles from '../styles/Home.module.css';
import { useSession } from 'next-auth/react';

import { signIn, signOut } from 'next-auth/react';

export default function Home() {
  const {data:session} = useSession();
  return (
    <div className={styles.container}>
      <Head>
        <title>Instagram Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/*Header*/}
      {!session&& 
        <div className={styles.beforeSignin}>
          <button className={styles.signinBtn} onClick={signIn}>
          Please Continue to Sign In</button>
          
        </div>
        }
        {session&&<Header/>}
 

      {/*Feed*/}
        {session&&<Feed/>}

      {/*Model*/}

    </div>
  )
}
